# przygotowanie do szukania
FIND_INIT(FFMPEG ffmpeg)

# szukanie
unset(FFMPEG_INCLUDE_DIR CACHE)	
FIND_STATIC(FFMPEG_LIBAVCODEC "avcodec<-54,?>")
FIND_STATIC(FFMPEG_LIBAVFORMAT "avformat<-54,?>")
FIND_STATIC(FFMPEG_LIBAVDEVICE "avdevice<-54,?>")
FIND_STATIC(FFMPEG_LIBAVUTIL "avutil<-51,?>")
FIND_STATIC(FFMPEG_LIBSWSCALE "swscale<-2,?>")	

# skopiowanie
FIND_FINISH(FFMPEG)

# sprawdzenie
if (FFMPEG_LIBAVCODEC_FOUND AND
	FFMPEG_LIBAVFORMAT_FOUND AND
	FFMPEG_LIBAVDEVICE_FOUND AND
	FFMPEG_LIBAVUTIL_FOUND AND
	FFMPEG_LIBSWSCALE_FOUND)
	set(FFMPEG_FOUND 1)
endif()