# przygotowanie do szukania
FIND_INIT(PREREQUISITES prerequisites)
unset(PREREQUISITES_INCLUDE_DIR CACHE)
if (WIN32) 
	#set(PREREQUISITES_FOUND 1)
	FIND_DLL(PREREQUISITES_LIB_AVCODEC 		"avcodec-54"    "avcodec-54"   )
	FIND_DLL(PREREQUISITES_LIB_AVDEVICE 	"avdevice-54"   "avdevice-54"  )
	FIND_DLL(PREREQUISITES_LIB_AVFILTER 	"avfilter-2"    "avfilter-2"   )
	FIND_DLL(PREREQUISITES_LIB_AVFORMAT 	"avformat-54"   "avformat-54"  )
	FIND_DLL(PREREQUISITES_LIB_AVUTIL 		"avutil-51"     "avutil-51"    )
	FIND_DLL(PREREQUISITES_LIB_GIFLIB 		"giflib4"       "giflib4"      )
	FIND_DLL(PREREQUISITES_LIB_GLUT 		"glut32"        "glut32"       )
	FIND_DLL(PREREQUISITES_LIB_EAY 			"libeay32"      "libeay32"     )
	#FIND_DLL(PREREQUISITES_LIB_PNG 			"libpng15"      "libpng15d"     )
	FIND_DLL(PREREQUISITES_LIB_TIFF 		"libtiff"       "libtiffd"      )
	FIND_DLL(PREREQUISITES_LIB_POSTPROC 	"postproc-52"   "postproc-52"  )
	FIND_DLL(PREREQUISITES_LIB_SSLEAY 		"ssleay32"      "ssleay32"     )
	FIND_DLL(PREREQUISITES_LIB_SWRESAMPLE 	"swresample-0"  "swresample-0" )
	FIND_DLL(PREREQUISITES_LIB_SWSCALE 		"swscale-2"     "swscale-2"    )
	if (
		PREREQUISITES_LIB_AVCODEC_FOUND 	AND
		PREREQUISITES_LIB_AVDEVICE_FOUND 	AND
		PREREQUISITES_LIB_AVFILTER_FOUND 	AND
		PREREQUISITES_LIB_AVFORMAT_FOUND 	AND
		PREREQUISITES_LIB_AVUTIL_FOUND 	 	AND
		PREREQUISITES_LIB_GIFLIB_FOUND 	 	AND
		PREREQUISITES_LIB_GLUT_FOUND 		AND
		PREREQUISITES_LIB_EAY_FOUND 		AND
		#PREREQUISITES_LIB_PNG_FOUND 		AND
		PREREQUISITES_LIB_TIFF_FOUND 	   	AND
		PREREQUISITES_LIB_POSTPROC_FOUND   	AND
		PREREQUISITES_LIB_SSLEAY_FOUND 	   	AND
		PREREQUISITES_LIB_SWRESAMPLE_FOUND 	AND
		PREREQUISITES_LIB_SWSCALE_FOUND 		
	)
		set(PREREQUISITES_FOUND 1)
	endif()
elseif (UNIX)
	

	# szukanie
	#FIND_SHARED(ZLIB "z<lib,?>" "zlib<lib,?>")
	#FIND_GLOB(PREREQUISITES_LIB_ "lib.so.*.*.*" "lib.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_AV_CODEC "libavcodec.so.*.*.*" "libavcodec.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_AV_DEVICE "libavdevice.so.*.*.*" "libavdevice.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_AV_FILTER "libavfilter.so.*.*.*" "libavfilter.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_AV_FORMAT "libavformat.so.*.*.*" "libavformat.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_AV_UTIL "libavutil.so.*.*.*" "libavutil.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_CRYPTO "libcrypto.so.*.*.*" "libcrypto.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_FREETYPE "libfreetype.so.*.*.*" "libfreetype.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_GIF "libgif.so.*.*.*" "libgif.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_GLUT "libglut.so.*.*" "libglut.so.*.*")
	FIND_GLOB(PREREQUISITES_LIB_JPEG "libjpeg.so.*.*.*" "libjpeg.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_MNG "libmng.so.*.*.*" "libmng.so.*.*.*")
	#FIND_GLOB(PREREQUISITES_LIB_PNG15 "libpng15.so.*.*.*" "libpng15.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_SSL "libssl.so.*.*.*" "libssl.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_SWRESAMPLE "libswresample.so.*.*.*" "libswresample.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_SWSCALE "libswscale.so.*.*.*" "libswscale.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_TIFF "libtiff.so.*.*.*" "libtiff.so.*.*.*")
	FIND_GLOB(PREREQUISITES_LIB_TIFFXX "libtiffxx.so.*.*.*" "libtiffxx.so.*.*.*")

	if (PREREQUISITES_LIB_AV_CODEC_FOUND AND
	PREREQUISITES_LIB_AV_DEVICE_FOUND AND
	PREREQUISITES_LIB_AV_FILTER_FOUND AND
	PREREQUISITES_LIB_AV_FORMAT_FOUND AND
	PREREQUISITES_LIB_AV_UTIL_FOUND AND
	PREREQUISITES_LIB_CRYPTO_FOUND AND
	PREREQUISITES_LIB_FREETYPE_FOUND AND
	PREREQUISITES_LIB_GIF_FOUND AND
	PREREQUISITES_LIB_GLUT_FOUND AND
	PREREQUISITES_LIB_JPEG_FOUND AND
	PREREQUISITES_LIB_MNG_FOUND AND
	#PREREQUISITES_LIB_PNG15_FOUND AND 
	PREREQUISITES_LIB_SSL_FOUND AND 
	PREREQUISITES_LIB_SWRESAMPLE_FOUND AND
	PREREQUISITES_LIB_SWSCALE_FOUND AND
	PREREQUISITES_LIB_TIFF_FOUND AND
	PREREQUISITES_LIB_TIFFXX_FOUND)
		set(PREREQUISITES_FOUND 1)
	endif()
endif()

# skopiowanie
FIND_FINISH(PREREQUISITES)